### PR TITLE
feat: Add Dark Mode

### PR DESCRIPTION
**Pull request by jalajcodes**
https://deploy-preview-6--max-quiz.netlify.app/

https://user-images.githubusercontent.com/17108695/154947970-c925727c-10f5-4899-8e0d-3325a606cde8.mp4

### CODE REVIEW

**Review by RahulSingh9131 — APPROVED** [review]
checked your code, everything looks good to me. Code is clean and understandable. Go ahead and merge.

**Review by sanjitsarkar — APPROVED** [review]
I think Using scss or any css preprocess is not allowed.
Btw code look good

**Review by KamiyaGaikwad — APPROVED** [review]
Looks good to merge

**Review by sanjitsarkar — APPROVED** [review]
Code looks clean but make sure to .gitignore .scss file as We aren't allowed to use any css preprocessor

**Comment by jalajcodes** [comment]
@sanjitsarkar In quiz app we can use sass.

**Pull request merged**
